extends:
  - airbnb-base
env:
  node: true
  mocha: true
  es6: true
rules:
  import/no-unresolved: 0
parser: typescript-eslint-parser
parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true
